site_name: DjangoStartA
site_url: ''

dev_addr:
    127.0.0.1:8101

theme:
  name: material

nav:
  - Home: index.md
  - howto_models: howto/models.md
  - howto_snippets: howto/snippets.md
  - notebook_snippets: notebook/snippets.md

markdown_extensions:
    - toc:
        permalink: True

use_directory_urls: false
docs_dir: docs
site_dir: site  
 